"""
filename: synthetic.py
description: Read-only repository over the synthetic JSON fixtures generated by
scripts/generate_synthetic_data.py. The fixtures were authored with an anchor
date of 2026-05-02 (see DATA_ANCHOR below). At load time we shift every
timestamp forward by (today - anchor) so meetings, news, tickets, and the
calendar always look fresh relative to the wall clock - no daily reseed
needed for the demo.
date: 03-05-2026
"""
__author__ = "Rodrigo Careaga"
__copyright__ = "Copyright 2026, Rodrigo Careaga"
__version__ = "0.1.0"
__status__ = "Development"

import json
from datetime import datetime, timedelta, timezone
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "synthetic"

# The anchor date matches scripts/generate_synthetic_data.py (NOW = 2026-05-02).
# Every timestamp in the JSON fixtures was authored relative to this anchor, so
# we shift by (today - anchor) at load time to keep the demo evergreen.
DATA_ANCHOR = datetime(2026, 5, 2, tzinfo=timezone.utc)

# Fields that hold ISO-8601 timestamps and need shifting.
_TIME_FIELDS = ("start_time", "end_time", "published_at", "created_at")


def _shift_delta() -> timedelta:
    """Days between the data anchor and 'now', clamped to non-negative.

    Clamping at zero means demos run on a clock-skewed laptop never produce
    timestamps in the past relative to the anchor; they just degrade to the
    original layout.
    """
    today = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    delta = today - DATA_ANCHOR
    if delta.days <= 0:
        return timedelta(0)
    return timedelta(days=delta.days)


def _shift_iso(value: str, delta: timedelta) -> str:
    """Shift one ISO-8601 timestamp forward by `delta`. Returns the input
    unchanged if it cannot be parsed."""
    if not isinstance(value, str) or not value:
        return value
    try:
        dt = datetime.fromisoformat(value)
    except ValueError:
        return value
    return (dt + delta).isoformat()


def _shift_record(record: Dict[str, Any], delta: timedelta) -> Dict[str, Any]:
    """Return a new dict with all known time fields shifted by `delta`."""
    if delta == timedelta(0):
        return record
    out = dict(record)
    for field in _TIME_FIELDS:
        if field in out and isinstance(out[field], str):
            out[field] = _shift_iso(out[field], delta)
    return out


def _shift_records(records: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
    delta = _shift_delta()
    return [_shift_record(r, delta) for r in records]


def _load(name: str) -> List[Dict[str, Any]]:
    path = DATA_DIR / f"{name}.json"
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def companies() -> List[Dict[str, Any]]:
    # No timestamps in companies; load as-is.
    return _load("companies")


@lru_cache(maxsize=1)
def news() -> List[Dict[str, Any]]:
    return _shift_records(_load("news"))


@lru_cache(maxsize=1)
def meetings() -> List[Dict[str, Any]]:
    return _shift_records(_load("meetings"))


@lru_cache(maxsize=1)
def transcripts() -> List[Dict[str, Any]]:
    # Transcripts have no timestamps; load as-is.
    return _load("transcripts")


@lru_cache(maxsize=1)
def tickets() -> List[Dict[str, Any]]:
    return _shift_records(_load("tickets"))


@lru_cache(maxsize=1)
def calendar() -> List[Dict[str, Any]]:
    return _shift_records(_load("calendar"))


def reset_cache() -> None:
    """Clear cached fixtures (used by tests after regenerating data)."""
    for fn in (companies, news, meetings, transcripts, tickets, calendar):
        fn.cache_clear()


def find_company(company_id: str) -> Optional[Dict[str, Any]]:
    return next((c for c in companies() if c["id"] == company_id), None)


def find_meeting(meeting_id: str) -> Optional[Dict[str, Any]]:
    return next((m for m in meetings() if m["id"] == meeting_id), None)


def news_for(company_id: str) -> List[Dict[str, Any]]:
    return [n for n in news() if n["company_id"] == company_id]


def tickets_for(company_id: str) -> List[Dict[str, Any]]:
    return [t for t in tickets() if t["company_id"] == company_id]


def transcript_for_meeting(meeting_id: str) -> Optional[Dict[str, Any]]:
    return next((t for t in transcripts() if t["meeting_id"] == meeting_id), None)


def past_transcripts_for(company_id: str) -> List[Dict[str, Any]]:
    return [t for t in transcripts() if t["company_id"] == company_id]


def upcoming_calendar() -> List[Dict[str, Any]]:
    return list(calendar())
