"""
filename: synthetic.py
description: Read-only repository over the synthetic JSON fixtures generated by scripts/generate_synthetic_data.py.
date: 03-05-2026
"""
__author__ = "Rodrigo Careaga"
__copyright__ = "Copyright 2026, Rodrigo Careaga"
__version__ = "0.1.0"
__status__ = "Development"

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional

DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "synthetic"


def _load(name: str) -> List[Dict[str, Any]]:
    path = DATA_DIR / f"{name}.json"
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def companies() -> List[Dict[str, Any]]:
    return _load("companies")


@lru_cache(maxsize=1)
def news() -> List[Dict[str, Any]]:
    return _load("news")


@lru_cache(maxsize=1)
def meetings() -> List[Dict[str, Any]]:
    return _load("meetings")


@lru_cache(maxsize=1)
def transcripts() -> List[Dict[str, Any]]:
    return _load("transcripts")


@lru_cache(maxsize=1)
def tickets() -> List[Dict[str, Any]]:
    return _load("tickets")


@lru_cache(maxsize=1)
def calendar() -> List[Dict[str, Any]]:
    return _load("calendar")


def reset_cache() -> None:
    """Clear cached fixtures (used by tests after regenerating data)."""
    for fn in (companies, news, meetings, transcripts, tickets, calendar):
        fn.cache_clear()


def find_company(company_id: str) -> Optional[Dict[str, Any]]:
    return next((c for c in companies() if c["id"] == company_id), None)


def find_meeting(meeting_id: str) -> Optional[Dict[str, Any]]:
    return next((m for m in meetings() if m["id"] == meeting_id), None)


def news_for(company_id: str) -> List[Dict[str, Any]]:
    return [n for n in news() if n["company_id"] == company_id]


def tickets_for(company_id: str) -> List[Dict[str, Any]]:
    return [t for t in tickets() if t["company_id"] == company_id]


def transcript_for_meeting(meeting_id: str) -> Optional[Dict[str, Any]]:
    return next((t for t in transcripts() if t["meeting_id"] == meeting_id), None)


def past_transcripts_for(company_id: str) -> List[Dict[str, Any]]:
    return [t for t in transcripts() if t["company_id"] == company_id]


def upcoming_calendar() -> List[Dict[str, Any]]:
    return list(calendar())
